---
title: "Blog 1: Data Progress"
description:  |
  Description of datasets found.
author: "TEAMATE"
date: "2025-02-24"
draft: FALSE
---


**Data #1:**
URL: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HLO4XC

The data comes from Kline, Patrick, Evan K. Rose, and Christopher
R. Walters, "Systemic Discrimination Among Large U.S. Employers,"
The Quarterly Journal of Economics, vol. 137 no. 4, (2022),
1963-2036.https://doi.org/10.1093/qje/qjac024. This dataset, published
alongside the article by Kline, Rose, and Walters (2022), examines potential
systemic hiring discrimination by large U.S. employers. The data primarily
cover hiring outcomes, employer characteristics, and applicant demographic
details spanning several years. Data is originally collected by authors. They
conducted a randomized control trail (RCT) to identify patterns of potential
discrimination, estimating the magnitude of these effects, and understanding
whether certain employer or regional characteristics are associated with
differential outcomes.

**Data #2:**
URL: https://catalog.data.gov/dataset/global-ecology-coral-reef-dataset-sully-et-al-2019

The dataset published in "A Global Analysis of Coral Bleaching Over the Past Two Decades" by Sully et al. (2019) examines large-scale patterns of coral bleaching worldwide, focusing on environmental drivers and spatial-temporal trends. The study compiles data from various sources, including satellite observations, in situ monitoring programs, and historical records spanning two decades. The dataset captures key variables such as bleaching severity and reef locations across multiple regions. However, a limitation is the absence of sea surface temperature data, which is a critical factor influencing coral bleaching. The authors supplemented this dataset with external sources, such as NOAA’s ocean temperature records with the aim to assess the influence of climate change on coral ecosystems and identify potential resilience factors.

One challenge in working with this data may involve cleaning and standardizing records from different sources to ensure consistency. Additionally, understanding potential biases in data collection such as uneven monitoring efforts across reef systems—will be important for drawing accurate conclusions. 

Sully, S., Burkepile, D.E., Donovan, M.K. et al. (2019). A global analysis of coral bleaching over the past two decades. Nature Communications, 10(1), 1264. https://doi.org/10.1038/s41467-019-09238-2
