---
title: "General Tips"
description:  |
  Some small but important tips to follow.
author: "Daniel Sussman"
date: "2024-10-04"
draft: FALSE
---


* Use the tidyverse!
* You don't have to tell me what kind of chart something is. For example, the below is not a useful start to a sentence.

> The graph presents a horizontal bar chart ...

* Each page should be largely standalone.
* Sometimes small tables or even inline numbers are better than a figure.
* Redundant colors (e.g. bar charts where each bar is a different color that doesn't signify anything) often don't help.
* Provide some details on how much data was removed in your cleaning process.
* **Use the tidyverse!**
* Imagine I'm an impatient boss. Show me only what is important and relevant.
* Cleaning must be entirely in R
* Don't say things like, well if only everyone did like so and so than everything would be better. There are many things hiding behind the data that would go to explain things.
This is an example of a bad conclusion.

>  The world could benefit form modeling its education systems after Europe's.

It is fine to talk about how the European system is better according to certain metrics, but don't assume that can easily translate to other regions.

* Don't talk about *your* "journey". The blog posts tell the story of your journey. The main pages should focus on the data and your findings.


# Use the tidyverse!


No but seriously, when asking ChatGPT to do your project for you, make sure to tell it to use the tidyverse, not base R.
